function atlas_labels = import_atlas_labels

%% Import data from text file.
% Script for importing data from the following text file:
%
%    X:\Stivers\projects\STAMP\Brainnetome\atlas.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/07/18 17:34:05

%% Initialize variables.
%filename = '/Users/cortneyhoward/Documents/RSA_Rotation/New_Stamp_Single_Trial/Analysis/brainnetome/atlas.txt';
%filename = '/Users/matthewslayton/Documents/Duke/Duke_Spring2022/FSL_class/atlas.txt';
filename = '/Users/matthewslayton/Library/CloudStorage/OneDrive-DukeUniversity/STAMP/atlas.txt';
delimiter = ' ';

%% Format for each line of text:
%   column1: double (%f)
%	column2: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
atlas_labels = table(dataArray{1:end-1}, 'VariableNames', {'Index','Label'});

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

end